version: "3"

services:
  catalog:
    build: ./BazarCatalogApi
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mohammed
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/BazarCatalogApi.pfx
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./BazarCatalogApi/Books.db:/app/Books.db
      - ./BazarCatalogApi.pfx:/root/.aspnet/https/BazarCatalogApi.pfx
    networks:
      - network
  order:
    build: ./BazarOrderApi
    ports:
    - "6000:80"
    - "6001:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mohammed
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/BazarOrderApi.pfx
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./BazarOrderApi/Orders.db:/app/Orders.db
      - ./BazarOrderApi.pfx:/root/.aspnet/https/BazarOrderApi.pfx
    networks:
      - network
    depends_on:
      - catalog
networks:
  network:
    driver: bridge